/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gspm;

/**
 *
 * @author ErikaYalitza
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(this);
    }

    //login objLogin = new login();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuAmdin = new javax.swing.JMenuItem();
        MenuSecretaria = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/motivacionalCuatro.jpg"))); // NOI18N

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        jMenu1.setText("Iniciar Sesion");
        jMenu1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        MenuAmdin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        MenuAmdin.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        MenuAmdin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/contraseña.png"))); // NOI18N
        MenuAmdin.setText("Administrador");
        MenuAmdin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAmdinActionPerformed(evt);
            }
        });
        jMenu1.add(MenuAmdin);

        MenuSecretaria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        MenuSecretaria.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        MenuSecretaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/contraseña.png"))); // NOI18N
        MenuSecretaria.setText("Secretaria");
        MenuSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSecretariaActionPerformed(evt);
            }
        });
        jMenu1.add(MenuSecretaria);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenu2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        menuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menuSalir.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icosalir25.png"))); // NOI18N
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu2.add(menuSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
      dispose();
    }//GEN-LAST:event_menuSalirActionPerformed

    private void MenuAmdinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAmdinActionPerformed
        Administrador a = new Administrador();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuAmdinActionPerformed

    private void MenuSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSecretariaActionPerformed
        Secretaria s = new Secretaria();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuSecretariaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAmdin;
    private javax.swing.JMenuItem MenuSecretaria;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JMenuItem menuSalir;
    // End of variables declaration//GEN-END:variables
}
