/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gspm;

/**
 *
 * @author ErikaYalitza
 */
public class Principal_secretaria extends javax.swing.JFrame {

    /**
     * Creates new form principal_secretaria
     */
    public Principal_secretaria() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        btnGestiondeArticulos = new javax.swing.JButton();
        btnGestionAlumnos = new javax.swing.JButton();
        btnventaArticulos = new javax.swing.JButton();
        btncobro = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bienvenid@ Secretari@");

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/principal.jpg"))); // NOI18N

        btnGestiondeArticulos.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnGestiondeArticulos.setText("Gestión de Articulos");
        btnGestiondeArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestiondeArticulosActionPerformed(evt);
            }
        });

        btnGestionAlumnos.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnGestionAlumnos.setText("Gestión de Alumnos");
        btnGestionAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionAlumnosActionPerformed(evt);
            }
        });

        btnventaArticulos.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnventaArticulos.setText("Venta de Articulos");
        btnventaArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnventaArticulosActionPerformed(evt);
            }
        });

        btncobro.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btncobro.setText("Cobro de Colegiaturas");
        btncobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncobroActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton5.setText("Cerrar sesion");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnventaArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGestiondeArticulos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 365, Short.MAX_VALUE)
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btncobro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGestionAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestiondeArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnventaArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncobro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jcMousePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionAlumnosActionPerformed
        JFrameGestionAlumno alumno = new JFrameGestionAlumno();
        alumno.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGestionAlumnosActionPerformed

    private void btnGestiondeArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestiondeArticulosActionPerformed
        GestionArticulos gestionarticulos = new GestionArticulos();
        gestionarticulos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestiondeArticulosActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btncobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncobroActionPerformed
        CobroColegiatura p = new CobroColegiatura();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncobroActionPerformed

    private void btnventaArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnventaArticulosActionPerformed
       this.dispose();
       Venta_articulos va = new Venta_articulos();
       va.setVisible(true);
    }//GEN-LAST:event_btnventaArticulosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionAlumnos;
    private javax.swing.JButton btnGestiondeArticulos;
    private javax.swing.JButton btncobro;
    private javax.swing.JButton btnventaArticulos;
    private javax.swing.JButton jButton5;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    // End of variables declaration//GEN-END:variables
}
