/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gspm;

/**
 *
 * @author ErikaYalitza
 */
public class Principal_Admin extends javax.swing.JFrame {

    /**
     * Creates new form principal_Admin
     */
    public Principal_Admin() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        btnGestionEmpleados = new javax.swing.JButton();
        btnBecas = new javax.swing.JButton();
        btngestiondeCategorias = new javax.swing.JButton();
        btngestiondeMensualidades = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bienvenido Administrador");

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/principal.jpg"))); // NOI18N

        btnGestionEmpleados.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnGestionEmpleados.setText("Gestion de Empleados");
        btnGestionEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionEmpleadosActionPerformed(evt);
            }
        });

        btnBecas.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnBecas.setText("Gestión de Becas");
        btnBecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBecasActionPerformed(evt);
            }
        });

        btngestiondeCategorias.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btngestiondeCategorias.setText("Gestion de Categorias");
        btngestiondeCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngestiondeCategoriasActionPerformed(evt);
            }
        });

        btngestiondeMensualidades.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btngestiondeMensualidades.setText("Gestion de Mensualidades");
        btngestiondeMensualidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngestiondeMensualidadesActionPerformed(evt);
            }
        });

        jButton5.setText("cerrar sesion");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btngestiondeCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(360, 360, 360)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                        .addComponent(btnBecas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(16, 16, 16))
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addComponent(btngestiondeMensualidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBecas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btngestiondeMensualidades, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btngestiondeCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142)
                .addComponent(jButton5)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionEmpleadosActionPerformed
       GestionEmpleado empleado = new GestionEmpleado();
       empleado.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnGestionEmpleadosActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnBecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBecasActionPerformed
        this.dispose();
        JFrameGestionBecas b = new JFrameGestionBecas();
        b.setVisible(true);
    }//GEN-LAST:event_btnBecasActionPerformed

    private void btngestiondeCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngestiondeCategoriasActionPerformed
       this.dispose();
        JFrameGestionCategorias gc = new  JFrameGestionCategorias();
        gc.setVisible(true);
    }//GEN-LAST:event_btngestiondeCategoriasActionPerformed

    private void btngestiondeMensualidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngestiondeMensualidadesActionPerformed
        this.dispose();
        JFrameGestionMensualidad gm = new JFrameGestionMensualidad();
        gm.setVisible(true);
    }//GEN-LAST:event_btngestiondeMensualidadesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBecas;
    private javax.swing.JButton btnGestionEmpleados;
    private javax.swing.JButton btngestiondeCategorias;
    private javax.swing.JButton btngestiondeMensualidades;
    private javax.swing.JButton jButton5;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    // End of variables declaration//GEN-END:variables
}
